import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/common/NavBar";
import Card from "../components/common/Card";
import Layout from "../components/Layout/Layout";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Koombea Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/subtract.svg" />
			</Head>
			<Layout></Layout>
		</div>
	);
};

export default Home;
